name: test_cloundbase
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+5
  firebase_storage: ^11.3.0  # ปรับเวอร์ชันให้เป็นเวอร์ชันล่าสุด
  firebase_core: ^2.15.1  # ใช้เวอร์ชันเดียวกัน
  cloud_firestore: <5.0.0
  firebase_auth: ^4.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  table_calendar: ^3.0.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/